### PR TITLE
Fix HTTP2 platform check to support curl versions <7.33.0

### LINKED ISSUE #827: Use of undefined constant CURL_VERSION_HTTP2 in vendor/microsoft/microsoft-graph/src/Http/GraphRequest.php on line 548
Hi 

I get "Use of undefined constant CURL_VERSION_HTTP2 in vendor/microsoft/microsoft-graph/src/Http/GraphRequest.php on line 548" with version 1.57.0 (PHP v7.4.28, cURL v7.29.0).

Thanks
galiganu

### PR DESCRIPTION
**Pull request by Ndiritu**
closes #827 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoftgraph/msgraph-sdk-php/pull/828)

### CODE REVIEW

File: src/Http/GraphRequest.php [hunk 1]
```diff
@@ -545,7 +545,7 @@ protected function createGuzzleClient()
             $clientSettings['verify'] = $this->proxyVerifySSL;
             $clientSettings['proxy'] = $this->proxyPort;
         }
-        if (extension_loaded('curl') && (curl_version()["features"] & CURL_VERSION_HTTP2 !== 0)) {
+        if (extension_loaded('curl') && defined(CURL_VERSION_HTTP2) && (curl_version()["features"] & CURL_VERSION_HTTP2 !== 0)) {
```
Comment (SilasKenneth) [inline src/Http/GraphRequest.php:548]:
```suggestion
        if (extension_loaded('curl') && defined('CURL_VERSION_HTTP2') && (curl_version()["features"] & CURL_VERSION_HTTP2 !== 0)) {

```

**Review by SilasKenneth — CHANGES_REQUESTED** [review]

**Review by SilasKenneth — APPROVED** [review]

**Review by SilasKenneth — DISMISSED** [review]

**Review by SilasKenneth — APPROVED** [review]
