### PR TITLE
Fix truncated error messages

### LINKED ISSUE #266: Dont truncate messages
Is there a way to allow errors to show fully. Whenever there is an exception, I get something like:

```
Client error: `POST https://graph.microsoft.com/v1.0/me/calendars/AAMkADQ0MTkyMDM1LTRhYWQtNGU5NC1iMTNiLWQwMGVkOTc3Njg0YgBGAAAAAADqewFH7jyUQLayRkU-YSm8BwCiRV4wB9ZcTLOUnr6Oobk4AAAAAAEGAACiRV4wB9ZcTLOUnr6Oobk4AABoPrhBAAA=/events` resulted in a `400 Bad Request` response:
{
"error": {
"code": "ErrorPropertyValidationFailure",
"message": "At least one property failed validation. (truncated...)
Exception
``` 

Which is very annoying since I don't know exactly what is wrong. 
[AB#7354](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7354)

### PR DESCRIPTION
**Pull request by Ndiritu**
### Context
When `http_errors = true` during creation of the Guzzle client, Guzzle throws a BadResponseException for 4xx and 5xx response status codes by default.

Our customer is able to handle this exception on their end however Guzzle truncates the exception message to 120 characters making it difficult for customers to know the cause of the issue (from the response body). e.g.
```
Client error: `POST https://graph.microsoft.com/v1.0/me/calendars/AAMkADQ0MTkyMDM1LTRhYWQtNGU5NC1iMTNiLWQwMGVkOTc3Njg0YgBGAAAAAADqewFH7jyUQLayRkU-YSm8BwCiRV4wB9ZcTLOUnr6Oobk4AAAAAAEGAACiRV4wB9ZcTLOUnr6Oobk4AABoPrhBAAA=/events` resulted in a `400 Bad Request` response:
{
"error": {
"code": "ErrorPropertyValidationFailure",
"message": "At least one property failed validation. (truncated...)
Exception

```

This is a known Guzzle issue with some reasonable arguments supporting the truncation by default:
- https://github.com/guzzle/guzzle/issues/1722#issuecomment-286260845

Guzzle 7.2 provides a way to work around this by configuring our default truncation limit (BodySummarizer param) (https://github.com/guzzle/guzzle/issues/2185#issuecomment-800293420). Doing this would warrant a major release due to a guzzle-http major dependency upgrade. Wrapping the exception works for now in my opinion however I'd recommend the major upgrade in v2

### Summary of this change
- Adds Utils method to wrap the Guzzle exception
- Updates execute() and executeAsync() methods to use Util functionality
- Adds tests for utils methods and exception scenarios during execute()/executeAsync()

Closes #266 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoftgraph/msgraph-sdk-php/pull/437)

### CODE REVIEW

File: src/Core/Utils.php [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+
+/**
+ * Class Utils
+ *
+ * @category Library
+ * @package  Microsoft.Graph
+ * @license  https://opensource.org/licenses/MIT MIT License
+ * @link     https://graph.microsoft.io/
+ */
+class Utils
```
Comment (zengin) [inline src/Core/Utils.php:31]: Please call this something more specific, e.g. `ExceptionWrapper`.

As the code evolves, people dump code into these generic looking packages/classes and classes like `Utils` become very convoluted.

Related reading: https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common

**Review by zengin — CHANGES_REQUESTED** [review]
Thanks for the awesome PR description!

**Review by MIchaelMainer — APPROVED** [review]
Approved contingent on change suggested by Mustafa.

**Review by SilasKenneth — APPROVED** [review]

File: src/Core/Utils.php (hunk 1 above)
Comment (Ndiritu) [reply src/Core/Utils.php]: Thanks for this suggestion & related reading @zengin . Made the change.

**Review by zengin — APPROVED** [review]

**Comment by guilliamxavier** [comment]
For the record, this breaks our app. See #451 and the linked PRs
