### PR TITLE
HOT FIX: Fix BC break in "Fix truncated error messages"

### LINKED ISSUE #451: Breaking change in 1.30.0 (Guzzle ClientException not caught anymore)
Updating from 1.29.0 to 1.30.0 (automatically by a `composer update`) broke our app. Relevant part:

```php
$graphRequest = $graph->createRequest($method, $endpoint);
try {
    $graphResponse = $graphRequest->execute();
} catch (\GuzzleHttp\Exception\ClientException $clientException) {
    $response = $clientException->getResponse();
    if ($response && $response->getStatusCode() === 400) {
        /* ... special handling of $response->getBody() ... */
    } else {
        throw $clientException; // rethrow
    }
}
```

(with Guzzle 6.5.5). Now, instead of our special handling, we get a PHP Fatal error:
> Uncaught Microsoft\\Graph\\Exception\\GraphException: [0]: Received 400 for call to https://*(redacted)*
> API response: *(redacted)*

Tracked down to #437, which converts *(not really "wraps", despite the naming)* `\GuzzleHttp\Exception\BadResponseException` to `\Microsoft\Graph\Exception\GraphException`. By the way, the fact that you had to modify the existing test https://github.com/microsoftgraph/msgraph-sdk-php/pull/437/commits/2105503c88ef63348c8941d158527be6a7735e42#diff-4ca1ed8036362337fd93a40c298121e56bb3eefeace0254f9ca40f152c2a68f1 proves that there's a BC break (given that GraphException does *not* extend BadResponseException, even less its children ClientException / ServerException).

I think there are ways to "fix" truncated error messages while preserving the exception type. I'll try to put up a PR. 
[AB#9148](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9148)

### PR DESCRIPTION
**Pull request by guilliamxavier**
Closes #451
Partially reverts #437

We just want the full (non-truncated) response body in the message, not change the exception type.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoftgraph/msgraph-sdk-php/pull/453)

### CODE REVIEW

File: src/Http/GraphRequest.php [hunk 1]
```diff
@@ -293,8 +293,6 @@ public function getTimeout()
     *
     * @param mixed $client The client to use in the request
     *
-    * @throws GraphException if response is invalid; if 4xx/5xx is returned and $http_errors is true
```
Comment (guilliamxavier) [inline src/Http/GraphRequest.php:296]: Actually this function has never thrown GraphException (before #437)

File: tests/Core/ExceptionWrapperTest.php [hunk 2]
```diff
@@ -4,30 +4,30 @@
...
     }
 
     public function testWrapBadResponseExceptionHasResponseBody()
     {
-        $responseBody = json_encode(array('body' => 'content'));
-        $ex = new BadResponseException("Error: API returned 400", new Request("GET", "/endpoint"), new Response(400, [], $responseBody));
-        $graphException = ExceptionWrapper::wrapGuzzleBadResponseException($ex);
-        $this->assertStringContainsString($responseBody, $graphException->getMessage());
+        $responseBody = json_encode(array('body' => bin2hex(random_bytes(120 / 2 + 1))));
+        $ex = GuzzleHttp\Exception\RequestException::create(new Request("GET", "/endpoint"), new Response(400, [], $responseBody));
```
Comment (guilliamxavier) [inline tests/Core/ExceptionWrapperTest.php:22]: This is to generate a truncated message

File: tests/Http/GraphRequestTest.php [hunk 3]
```diff
@@ -170,6 +169,11 @@ public function testExecuteAsync()
                          ->executeAsync($this->client);
         $this->assertInstanceOf(GuzzleHttp\Promise\PromiseInterface::class, $promise);
 
+        $promise = $this->requests[0]
+                         ->executeAsync($this->client);
+        $promise2 = $this->requests[2]
+                          ->executeAsync($this->client);
+
```
Comment (guilliamxavier) [inline tests/Http/GraphRequestTest.php:176]: Restored from #437 that removed them without explanation

File: tests/Http/HttpTest.php [hunk 4]
```diff
@@ -84,7 +84,7 @@ public function testDelete()
 
     public function testInvalidVerb()
     {
-        $this->expectException(GraphException::class);
+        $this->expectException(GuzzleHttp\Exception\ClientException::class);
```
Comment (guilliamxavier) [inline tests/Http/HttpTest.php:87]: Reverted from #437

File: tests/Http/GraphRequestTest.php [hunk 5]
```diff
@@ -204,20 +208,20 @@ public function testGetConcatenator()
 
     public function testExecuteWith4xxResponse()
     {
-        $this->expectException(GraphException::class);
+        $this->expectException(GuzzleHttp\Exception\ClientException::class);
```
Comment (guilliamxavier) [inline tests/Http/GraphRequestTest.php:211]: This test was added by #437

File: src/Core/ExceptionWrapper.php [hunk 6]
```diff
@@ -35,12 +34,41 @@ class ExceptionWrapper
...
-        return new GraphException($errMsg);
+        $response = $ex->getResponse();
+
+        // Safety check for Guzzle < 7.0
+        if (!$response) {
+            return $ex;
+        }
+
+        /** @see \GuzzleHttp\Exception\RequestException::create() */
+        if (preg_match('/^(.+: `.+ .+` resulted in a `.+ .+` response)($|:\n)/U', $ex->getMessage(), $match)) {
```
Comment (guilliamxavier) [inline src/Core/ExceptionWrapper.php:49]: This is to modify only potentially truncated messages, not manually-constructed exceptions like e.g. https://github.com/guzzle/guzzle/blob/7.3.0/src/RedirectMiddleware.php#L211 that purposedly *doesn't* include the response body

**Review by guilliamxavier — COMMENTED** [review]
I have added some explanations for reviewers

File: src/Core/ExceptionWrapper.php [hunk 7]
```diff
@@ -35,12 +34,41 @@ class ExceptionWrapper
...
+            $message = $match[1];
+
+            $body = $response->getBody();
+            $summary = $body->getContents();
+            if ($body->isSeekable()) {
```
Comment (Ndiritu) [inline src/Core/ExceptionWrapper.php:54]: Like this check

File: src/Core/ExceptionWrapper.php [hunk 8]
```diff
@@ -35,12 +34,41 @@ class ExceptionWrapper
...
+                $body->rewind();
+            }
+
+            if ($summary !== '') {
+                $message .= ":\n{$summary}\n";
+
+                //return new $ex($message, $ex->getRequest(), $ex->getResponse(), $ex, $ex->getHandlerContext());
+                // Better: modify internal message inside original exception object (preserves the stack trace)
+                (new class() extends \Exception {
```
Comment (Ndiritu) [inline src/Core/ExceptionWrapper.php:63]: Curious why this needs to be an anonymous class

File: src/Http/GraphRequest.php (hunk 1 above)
Comment (Ndiritu) [reply src/Http/GraphRequest.php:296]: Agreed, true.

File: src/Http/GraphRequest.php [hunk 9]
```diff
@@ -401,7 +399,7 @@ function ($reason) {
     * @param string $path   The path to download the file to
     * @param mixed  $client The client to use in the request
     *
-     * @throws GraphException if file path is invalid; if \GuzzleHttp\Exception\BadResponseException is thrown for 4xx/5xx responses
+     * @throws GraphException if file path is invalid
      *
```
Comment (Ndiritu) [inline src/Http/GraphRequest.php:403]: I think we can add an additional `@throws` for BadResponseException since we handle that on line 435?

File: tests/Http/GraphRequestTest.php (hunk 3 above)
Comment (Ndiritu) [reply tests/Http/GraphRequestTest.php:176]: Thanks for catching this. The two extra promises did not seem to be used meaningfully for an assertion. However I notice now that we're trying to unwrap a list of promises & ensure they get fulfilled yielding a GraphResponse obj. Perhaps we could add all the promises to an array so that the loop afterwards is useful?

**Review by Ndiritu — CHANGES_REQUESTED** [review]
Overall, I prefer these changes to #452 . Cleaner i.e. no extra sub-classes, safer checks before overwriting the exception message & resetting the seek offset if needed.

Some questions/comments added

File: src/Core/ExceptionWrapper.php [hunk 10]
```diff
@@ -35,12 +34,41 @@ class ExceptionWrapper
...
+                    public function overwriteProtectedMessage(\Exception $ex, $message)
```
Comment (Ndiritu) [inline src/Core/ExceptionWrapper.php:64]: Curious why this needs to be in an anonymous class

File: tests/Http/GraphRequestTest.php (hunk 3 above)
Comment (guilliamxavier) [reply tests/Http/GraphRequestTest.php:176]: I prefer not touch unrelated code. Even without assertion, this at least "tests" that these extra calls don't throw. Also that re-executes and re-assigns `$promise`, maybe on purpose? So I think better left for another PR :wink:

File: src/Http/GraphRequest.php (hunk 9 above)
Comment (guilliamxavier) [reply src/Http/GraphRequest.php:403]: Not sure. Actually the functions `execute()`, `download()` and `upload()` all can potentially throw any GuzzleException (including but not limited to BadResponseException), and we don't really "handle" it (only un-truncate the message)... Maybe add `@throws GuzzleException` then?

File: src/Core/ExceptionWrapper.php (hunk 10 above)
Comment (guilliamxavier) [reply src/Core/ExceptionWrapper.php:64]: Internal implementation detail? Actually there are other ways to do `$ex->message = $message;` (which we can't do directly because the property is `protected`):
```php
(function () use ($message) { $this->message = $message; })->call($ex);
```
or:
```php
$rp = new \ReflectionProperty(\Exception::class, 'message');
$rp->setAccessible(true);
$rp->setValue($ex, $message);
```
but I find them more "risky"... WDYT?

File: src/Http/GraphRequest.php (hunk 9 above)
Comment (Ndiritu) [reply src/Http/GraphRequest.php]: Good point. `@throws GuzzleException` makes sense. And yes sorry, we don't "handle" it, wrong word 😄

File: src/Core/ExceptionWrapper.php (hunk 10 above)
Comment (Ndiritu) [reply src/Core/ExceptionWrapper.php]: Makes sense considering the property is `protected`.

File: tests/Http/GraphRequestTest.php (hunk 3 above)
Comment (Ndiritu) [reply tests/Http/GraphRequestTest.php:175]: Sure. Not aware of the intention of re-assigning `$promise` in this case but yes this can be handled in another PR

**Comment by guilliamxavier** [comment]
Thanks for reviewing @Ndiritu 🙂 Are you still requesting changes after my last force-pushes?

**Comment by Ndiritu** [comment]
Nope. Sorry didn't notice the force-push included the `@throws GuzzleException`. Approved.
I'll give room for one more reviewer to second

**Review by Ndiritu — APPROVED** [review]

**Review by MIchaelMainer — APPROVED** [review]
Makes sense to me. Thank you for the pull request!
